# Generating Nonograms

In [1]:
import random
import numpy as np
from bisect import bisect_left
from tqdm import tqdm

In [2]:
def n_gen(a, N=8):
    """
    N: size of N*N nonogram
    a: number of coloured tiles in nonogram
    return two arrays: two numpy arrays of column conditions and row conditions, and the corresponding nonogram (2d array)
    What is asserted: the majority o
    """
    assert isinstance(N, int)
    assert isinstance(a, int)
    
    # Generate nonogram with random
    numlist = list(range(0, N*N))

    # coloured_list is the list of indices of the coloured blocks
    coloured_list = random.sample(numlist, a)

    # empty_list is the list of indices of empty (white) blocks
    empty_list = list(set(numlist) - set(coloured_list))

    nonogram = [ [0]*N for i in range(0, N)]

    for el in coloured_list:
        nonogram[el//N][el%N] = 1
    
    nonogram = np.array(nonogram)


    row_condition = []
    column_condition = []

    
    # get row conditions (row representations)

    for i in range(0, N):
        # list of indices of empty (white) blocks of the corresponding row
        row_empty_list = [i*N-1] + empty_list[bisect_left(empty_list, i*N):bisect_left(empty_list, (i+1)*N)] + [(i+1)*N]
        
        # represent row conditions
        diff_row = np.diff(row_empty_list) - 1

        row_condition.append([el for el in diff_row if el != 0])



    # get column conditions (column representations)

    converted_empty_list = sorted([(N*(el%N)+(el//N)) for el in empty_list])

    for i in range(0, N):

        column_empty_list = [i*N-1] + converted_empty_list[bisect_left(converted_empty_list, i*N):bisect_left(converted_empty_list, (i+1)*N)] + [(i+1)*N]
        
        diff_row = np.diff(column_empty_list) - 1

        column_condition.append([el for el in diff_row if el != 0])


    # print(sorted(coloured_list))
    # print(nonogram)
    # print(row_condition)
    # print(column_condition)
    return np.array([row_condition, column_condition]), nonogram


In [3]:
condition, nonogram = n_gen(32, 8)

In [4]:
print('row condition: ', end = "\n")
print(*list(condition[0]))
# print(*list(condition[0]), sep = '\n')
print('column condition: ', end = "\n")
print(*list(condition[1]))
# print(*list(condition[1]), sep = '\n')
print(nonogram)

row condition: 
[1, 1] [3, 2] [1, 1, 1] [1, 1, 1, 1] [1, 1, 1] [4, 1, 1] [5] [2, 1, 1]
column condition: 
[3, 2] [1, 2] [1, 4] [2, 3] [1, 1] [6, 1] [] [1, 3, 1]
[[0 0 0 0 0 1 0 1]
 [1 1 1 0 1 1 0 0]
 [1 0 0 1 0 1 0 0]
 [1 0 0 1 0 1 0 1]
 [0 0 1 0 0 1 0 1]
 [1 1 1 1 0 1 0 1]
 [1 1 1 1 1 0 0 0]
 [0 0 1 1 0 1 0 1]]


In [5]:
type(condition), condition.shape, type(nonogram), nonogram.shape

(numpy.ndarray, (2, 8), numpy.ndarray, (8, 8))

In [7]:
# Create Training dataset
X_train = []
Y_train = []

for i in [20, 22, 24, 26, 28, 30]:
    for j in tqdm(range(10000)):
        condition, nonogram = n_gen(a = i, N = 8)
        X_train.append(condition)
        Y_train.append(nonogram)

X_train = np.array(X_train)
Y_train = np.array(Y_train)

print(X_train.shape)
print(Y_train.shape)

100%|██████████| 10000/10000 [00:08<00:00, 1164.94it/s]


(60000, 2, 8)
(60000, 8, 8)


In [8]:
# Save train data
print('Saving...', flush = True)
np.save('./data/X_train.npy', X_train)
np.save('./data/Y_train.npy', Y_train)
print('Done')

Saving...
Done


In [9]:
del X_train, Y_train

In [10]:
# Create Test dataset
X_test = []
Y_test = []

for i in [25]:
    for j in tqdm(range(10000)):
        condition, nonogram = n_gen(a = i, N = 8)
        X_test.append(condition)
        Y_test.append(nonogram)

X_test = np.array(X_test)
Y_test = np.array(Y_test)

print(X_test.shape)
print(Y_test.shape)

100%|██████████| 10000/10000 [00:10<00:00, 980.43it/s]

(10000, 2, 8)
(10000, 8, 8)


In [11]:
# Save train data
print('Saving...', flush = True)
np.save('./data/X_test.npy', X_test)
np.save('./data/Y_test.npy', Y_test)
print('Done')

Saving...
Done
